package lab2;
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 *   Class          LoanCalculator 
 *   File           LoanCalculator.java 
 *   Description    Calculates a monthly loan payment given loan amount,
 *                  interest rate, and years of loan
 *   @author:       Koenn Becker
 *   Environment    PC, Windows 10, jdk1.8.0_151, NetBeans 8.2
 *   Date:           1/8/2018
 *   @version        1.0.0 
 *   @see            javax.swing.JOptionPane 
 *   History Log 
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Koenn Becker
 */
public class LoanCalculator extends javax.swing.JFrame {

    /**
     * Creates new form loanGUI
     */
    public LoanCalculator() {
        initComponents();
        this.setLocationRelativeTo(null); // Centers forms
        SwingUtilities.getRootPane(calculateJButton).setDefaultButton(calculateJButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcCounterJLabel = new javax.swing.JLabel();
        calcCounterJTextField = new javax.swing.JTextField();
        principalJLabel = new javax.swing.JLabel();
        principalJTextField = new javax.swing.JTextField();
        rateJLabel = new javax.swing.JLabel();
        rateJTextField = new javax.swing.JTextField();
        yearsJLabel = new javax.swing.JLabel();
        yearsJTextField = new javax.swing.JTextField();
        calculateJButton = new javax.swing.JButton();
        paymentJTextField = new javax.swing.JTextField();
        interestJLabel = new javax.swing.JLabel();
        interestJTextField = new javax.swing.JTextField();
        clearJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Calculator");
        setMinimumSize(new java.awt.Dimension(100, 193));
        setPreferredSize(new java.awt.Dimension(350, 400));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 3, 3));

        calcCounterJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calcCounterJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calcCounterJLabel.setText("Calculation Counter:");
        getContentPane().add(calcCounterJLabel);

        calcCounterJTextField.setEditable(false);
        calcCounterJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calcCounterJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calcCounterJTextField.setPreferredSize(new java.awt.Dimension(15, 23));
        getContentPane().add(calcCounterJTextField);

        principalJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        principalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        principalJLabel.setText("Enter the loan amount:");
        getContentPane().add(principalJLabel);

        principalJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        principalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(principalJTextField);

        rateJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rateJLabel.setText("Enter interest rate as %:");
        getContentPane().add(rateJLabel);

        rateJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rateJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rateJTextField.setToolTipText("Enter rate as percent withouth % symbol");
        getContentPane().add(rateJTextField);

        yearsJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearsJLabel.setText("Enter years of loan:");
        getContentPane().add(yearsJLabel);

        yearsJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearsJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(yearsJTextField);

        calculateJButton.setBackground(new java.awt.Color(255, 255, 204));
        calculateJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate Payment");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calculateJButton);

        paymentJTextField.setEditable(false);
        paymentJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paymentJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(paymentJTextField);

        interestJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        interestJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        interestJLabel.setText("Interest Paid:");
        getContentPane().add(interestJLabel);

        interestJTextField.setEditable(false);
        interestJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        interestJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(interestJTextField);

        clearJButton.setBackground(new java.awt.Color(255, 255, 204));
        clearJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearJButton.setMnemonic('R');
        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearJButton);

        quitJButton.setBackground(new java.awt.Color(255, 255, 204));
        quitJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitJButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int counter = 0;
    
    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
        // Calculate the loan payment
        try {
            // Gets inputs from text fieleds
            double amount = Double.parseDouble(principalJTextField.getText());
            double rate = Double.parseDouble(rateJTextField.getText());
            double years = Double.parseDouble(yearsJTextField.getText());
            boolean invalidInputs = (amount < 0 || amount > 1000000000 || 
                    rate < 0 || rate > 100 || years < 0 || years > 100);
            
            if (invalidInputs)
                throw new NumberFormatException();
            else {
                // Calculate payment using formula
                counter ++;
                double payment = (amount * rate/1200)/(1 - 
                        Math.pow((1 + rate/1200), years * (-12)));
                double interest = years * payment * 12 - amount;
                DecimalFormat dollars = new DecimalFormat("$#,##0.00");
                String result = dollars.format(payment);
                
                // Display results to according textfields
                calcCounterJTextField.setText(String.valueOf(counter));
                paymentJTextField.setText(result);
                interestJTextField.setText(dollars.format(interest));
            }
        }
        catch(NumberFormatException nume){
            JOptionPane.showMessageDialog(null,
                    "Please enter a positive number for all required fields",
                    "Input Error", JOptionPane.WARNING_MESSAGE);
            principalJTextField.requestFocus();
            principalJTextField.selectAll();
        }
    }//GEN-LAST:event_calculateJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // Clears all text fields and resets focus
        
        principalJTextField.setText("");
        rateJTextField.setText("");
        paymentJTextField.setText("");
        interestJTextField.setText("");
        yearsJTextField.setText("");   
        
    }//GEN-LAST:event_clearJButtonActionPerformed

    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        // Quits the application
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
     *<pre>     
     *   Method:        main()     
     *   Description    Calculates monthly payment. Relies on two     
     *                  member methods: inputDouble and payment    
     *   @param         args are the command line strings     
     *   @author        Koenn Becker   
     *   Date           1/8/2018  
     *<pre>     
     *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calcCounterJLabel;
    private javax.swing.JTextField calcCounterJTextField;
    private javax.swing.JButton calculateJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JLabel interestJLabel;
    private javax.swing.JTextField interestJTextField;
    private javax.swing.JTextField paymentJTextField;
    private javax.swing.JLabel principalJLabel;
    private javax.swing.JTextField principalJTextField;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel rateJLabel;
    private javax.swing.JTextField rateJTextField;
    private javax.swing.JLabel yearsJLabel;
    private javax.swing.JTextField yearsJTextField;
    // End of variables declaration//GEN-END:variables
}
