package lab2; 

// Imports classes needed
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *  Calculates a monthly loan payment given loan amount,
 *  interest rate, and years of loan. Uses Java Swing for GUI
 *  <p>
 *  Environment:    PC, Windows 10, JDK 1.8.0_151, NetBeans 8.2
 *  <p>
 *  Date:           1/10/2018 
 *  <p>
 *  History Log:    1/8/2018
 *  <p>
 *  @author         Koenn Becker
 *  @version        1.0.0
 */
public class loanGUI extends javax.swing.JFrame {

    int counter = 0;    // Sets a class variable for counter text field
    
    /**
     * Creates new form loanGUI<br>
     * Sets form position to center of screen<br>
     * Sets default button to {@link #calculateJButton}<br>
     * Sets icon for form<br>
     * Sets the current date on form<br>
     * @see initComponents
     * @see #setDate() 
     */
    
    public loanGUI() {
        initComponents();
        this.setLocationRelativeTo(null); // Centers forms
        this.getRootPane().setDefaultButton(calculateJButton); // Sets default button
        
        // Set icon for form
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/lab2/planeIcon.png"));
        // Sets focused field
        principalJTextField.requestFocus();
        // Sets current date and adds it to form title
        setDate();
    }
    /**        
     *  Method          setDate()     
     *  Description:    Creates new SimpleDateFormat<br>
     *                  Sets date and then adds it to form title<br>
     *  Date Created:           1/10/2018  
     *  @author         Koenn Becker
     *  @see            java.text.DateFormat
     *  @see            java.text.SimpleDateFormat
     *  @see            java.util.Date 
     */ 
    private void setDate() {
        
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        Date date = new Date();
        this.setTitle("Loan Calculator -- " + dateFormat.format(date));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcCounterJLabel = new javax.swing.JLabel();
        calcCounterJTextField = new javax.swing.JTextField();
        principalJLabel = new javax.swing.JLabel();
        principalJTextField = new javax.swing.JTextField();
        rateJLabel = new javax.swing.JLabel();
        rateJTextField = new javax.swing.JTextField();
        yearsJLabel = new javax.swing.JLabel();
        yearsJTextField = new javax.swing.JTextField();
        calculateJButton = new javax.swing.JButton();
        paymentJTextField = new javax.swing.JTextField();
        interestJLabel = new javax.swing.JLabel();
        interestJTextField = new javax.swing.JTextField();
        clearJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Calculator");
        setMinimumSize(new java.awt.Dimension(100, 193));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 3, 3));

        calcCounterJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calcCounterJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calcCounterJLabel.setText("Calculation Counter:");
        getContentPane().add(calcCounterJLabel);

        calcCounterJTextField.setEditable(false);
        calcCounterJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calcCounterJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calcCounterJTextField.setPreferredSize(new java.awt.Dimension(15, 23));
        getContentPane().add(calcCounterJTextField);

        principalJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        principalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        principalJLabel.setText("Enter the loan amount:");
        getContentPane().add(principalJLabel);

        principalJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        principalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(principalJTextField);

        rateJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rateJLabel.setText("Enter interest rate as %:");
        getContentPane().add(rateJLabel);

        rateJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rateJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rateJTextField.setToolTipText("Enter rate as percent withouth % symbol");
        getContentPane().add(rateJTextField);

        yearsJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearsJLabel.setText("Enter years of loan:");
        getContentPane().add(yearsJLabel);

        yearsJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearsJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(yearsJTextField);

        calculateJButton.setBackground(new java.awt.Color(255, 255, 204));
        calculateJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate Payment");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calculateJButton);

        paymentJTextField.setEditable(false);
        paymentJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paymentJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(paymentJTextField);

        interestJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        interestJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        interestJLabel.setText("Interest Paid:");
        getContentPane().add(interestJLabel);

        interestJTextField.setEditable(false);
        interestJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        interestJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(interestJTextField);

        clearJButton.setBackground(new java.awt.Color(255, 255, 204));
        clearJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearJButton.setMnemonic('R');
        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearJButton);

        quitJButton.setBackground(new java.awt.Color(255, 255, 204));
        quitJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitJButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
     /**        
     *  Event handler   calculateJButtonActionPerformed    
     *  Description:    This is the central method of the program. It is ran when {@link #calculateJButton} is pressed.
     *                  There are many parts to this method: Local variable initialization, 
     *                  input validation using a try/catch block, store inputs from text fields,
     *                  calculation counter, actual calculation formula, dollar DecimalFormat, displaying output to
     *                  appropriate fields, and exception to be thrown if invalidInput.<p>
     *  Date Created:   1/10/2018
     *  @param          evt
     *  @author         Koenn Becker
     *  @see            java.text.DecimalFormat
     *  @exception      NumberFormatException When invalidInput is true
     *  @see            NumberFormatException
     */  
    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
        // Calculates the loan payment
        
        
        // Defines constants
        final double MAX_AMOUNT = 1000000000;
        final double MAX_INTEREST_RATE = 100;
        final int COMPOUNDINGS = 12;
        final double MAX_YEARS = 50;
        final double PERIOD_INTEREST = COMPOUNDINGS * 100;
        
        // Error message to be displayed when NumberFormatException is thrown
        String errorMessage = "Please enter a positive number for all required fields and insure that no characters are entered." +
                "\nLoan amount must be in range [(0 - " + MAX_AMOUNT + "]" +
                "\nInterest rate must be in range ([0 - " + MAX_INTEREST_RATE + "]" +
                "\nYears must be in range ([0 - " + MAX_YEARS + "]";
        
        
        try {   // Try block tests code inside and if invalidInputs is true, throws exception
            
            // Gets inputs from text fieleds
            double amount = Double.parseDouble(principalJTextField.getText());
            double rate = Double.parseDouble(rateJTextField.getText());
            double years = Double.parseDouble(yearsJTextField.getText());

            boolean invalidInput = (amount < 0 || amount > MAX_AMOUNT || 
                    rate < 0 || rate > MAX_INTEREST_RATE || years < 0 || years > MAX_YEARS);
            
            if (invalidInput)
                
                throw new NumberFormatException();

            else {      // This code runs if invalidInput is false
                
                // Calculate payment using formula
                counter ++;     // Increases the counter variable by 1
                double payment = (amount * rate/PERIOD_INTEREST)/
                        (1 - Math.pow((1 + rate/PERIOD_INTEREST), years * (-COMPOUNDINGS)));
                
                double interest = years * COMPOUNDINGS * payment - amount;
                
                // Result formatting mask
                DecimalFormat dollars = new DecimalFormat("$#,##0.00");
                
                // Display results to according textfields
                calcCounterJTextField.setText(String.valueOf(counter));
                paymentJTextField.setText(dollars.format(payment));
                interestJTextField.setText(dollars.format(interest));
            }
        }
        // When NumberFormatException is thrown, the following code block is ran
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, errorMessage, "Input Error", 
                    JOptionPane.WARNING_MESSAGE);
            principalJTextField.requestFocus();
            principalJTextField.selectAll();
                
        }
        
    }//GEN-LAST:event_calculateJButtonActionPerformed
    
    /**        
     *  Event handler   clearJButtonActionPerformed    
     *  Description:    This event handler clears all text fields(except the calculation counter) by {@code .setText("")} 
     *                  and resets focus to {@link #principalJTextField}.<p>
     *  Date Created:   1/10/2018 
     *  @param          evt
     *  @author         Koenn Becker
     *  @see            javax.swing.text.JTextComponent#setText
     */  
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // Clears all text fields and resets focus
        
        principalJTextField.setText("");
        rateJTextField.setText("");
        paymentJTextField.setText("");
        interestJTextField.setText("");
        yearsJTextField.setText("");
        
        principalJTextField.requestFocus(); // Resets focus
        
    }//GEN-LAST:event_clearJButtonActionPerformed

     /**        
     *  Event handler   quitJButtonActionPerformed    
     *  Description:    This event handler terminates the application using {@code System.exit(0)}.<p>
     *  Date Created:   1/10/2018 
     *  @param          evt
     *  @author         Koenn Becker
     */
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        // Quits the application
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    /**        
     *  Method         main()    
     *  Description:   Creates new {@link #loanGUI()} object and sets it to visible.
     *                  Also uses try catch block to halt the thread so LoanCalcSplash.gif can run
     *  @param         args Unused.     
     *  @author        Koenn Becker   
     *  Date Created:  1/10/2018  
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                // Halts the running thread for length of splash screen gif in milliseconds
                try {
                    Thread.sleep(1650);
                }
                catch(InterruptedException e) {
                }
                
                // Creats new form Object and sets it visible
                new loanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calcCounterJLabel;
    private javax.swing.JTextField calcCounterJTextField;
    private javax.swing.JButton calculateJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JLabel interestJLabel;
    private javax.swing.JTextField interestJTextField;
    private javax.swing.JTextField paymentJTextField;
    private javax.swing.JLabel principalJLabel;
    private javax.swing.JTextField principalJTextField;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel rateJLabel;
    private javax.swing.JTextField rateJTextField;
    private javax.swing.JLabel yearsJLabel;
    private javax.swing.JTextField yearsJTextField;
    // End of variables declaration//GEN-END:variables
    
}
